cfg:
  disagreement_files: ["/home/david/Code/kalos/results/instance_segmentation/texbig/texbig_segm_iou_do_de.json",
                       "/home/david/Code/kalos/results/instance_segmentation/texbig/texbig_segm_giou_do_de.json",
                       "/home/david/Code/kalos/results/instance_segmentation/texbig/texbig_segm_centroid_do_de.json"]
  output_dir: /home/david/Code/kalos/results/instance_segmentation/texbig
  log_level: INFO
  font_scale: 2.5
